services:
  server:
    build: ./server/
    volumes:
      - ./server/main:/main/app
    env_file:
      - .env
    ports:
      - "8000:8000"
    restart: unless-stopped

  frontend:
    build: ./client/
    ports:
      - '8080:80'
    environment:
      - API_BASE=${API_BASE}
    restart: unless-stopped
