volumes:
  server:

services:
  server:
    build: app/server/
    volumes:
      - server:/main/app
    env_file:
      - .env
    ports:
      - "8000:8000"
    restart: unless-stopped

  client:
    build: app/client/
    ports:
      - '8080:80'
    environment:
      - API_BASE=${API_BASE}
    restart: unless-stopped
